### ISSUE TITLE
Torches work without fuel

### ISSUE THREAD

**Issue by D-A-R-K-N-E-S-S** [TastyChickenLegs/TimedTorchesStayLit#1]
With the setting "Allow Adding Fuel = true", the torches (brazier, etc) consume fuel - however once depleted they continue to work without fuel.

Running this mod on my dedicated server with 5 clients who all have the mod and configs are synced.

Also, thank you for the mod.

**Comment by TastyChickenLegs** [comment]
Hmm ok let me look at this.  I changed a good portion of the codebase and it could be a bug.  Thanks again.

**Comment by TastyChickenLegs** [comment]
Ok I see the bug.  I will update this today.  Thanks for letting me know.

**Comment by D-A-R-K-N-E-S-S** [comment]
Thank you, appreciate the quick fix!

**Comment by TastyChickenLegs** [comment]
Yea sure have a great day.
